// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFhdomD4yf_AD6bDFPToUxbbN1gRPY70U',
    appId: '1:991402422958:web:420ed49b382dfb4416f33f',
    messagingSenderId: '991402422958',
    projectId: 'bus-ease-cf06b',
    authDomain: 'bus-ease-cf06b.firebaseapp.com',
    storageBucket: 'bus-ease-cf06b.appspot.com',
    measurementId: 'G-2CJ9K2F5P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Qvqf2CTchCK0XLCxbBwtCiOEkYD9HIo',
    appId: '1:991402422958:android:0d08ebd6d7789aba16f33f',
    messagingSenderId: '991402422958',
    projectId: 'bus-ease-cf06b',
    storageBucket: 'bus-ease-cf06b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTeimTRtWi7cDc-9kxw6BiJ7vWcgRHtUs',
    appId: '1:991402422958:ios:a6d989ea473cf3a016f33f',
    messagingSenderId: '991402422958',
    projectId: 'bus-ease-cf06b',
    storageBucket: 'bus-ease-cf06b.appspot.com',
    iosBundleId: 'com.azfar.busEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTeimTRtWi7cDc-9kxw6BiJ7vWcgRHtUs',
    appId: '1:991402422958:ios:a6d989ea473cf3a016f33f',
    messagingSenderId: '991402422958',
    projectId: 'bus-ease-cf06b',
    storageBucket: 'bus-ease-cf06b.appspot.com',
    iosBundleId: 'com.azfar.busEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFhdomD4yf_AD6bDFPToUxbbN1gRPY70U',
    appId: '1:991402422958:web:52120e35f77693e416f33f',
    messagingSenderId: '991402422958',
    projectId: 'bus-ease-cf06b',
    authDomain: 'bus-ease-cf06b.firebaseapp.com',
    storageBucket: 'bus-ease-cf06b.appspot.com',
    measurementId: 'G-Z0TPVTX8N6',
  );
}
